version: '3.3'

services:
  ldc-dynamo:
    image: amazon/dynamodb-local
    container_name: ldc-dynamo
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb"]

  ldc-scrapper:
    build: "./scrapper"
    container_name: ldc-scrapper
    links:
    - ldc-dynamo:ldc-dynamo
    environment:
      DYNAMO_ENDPOINT: "http://ldc-dynamo:8000"
      AWS_REGION: "us-west-2"
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    depends_on:
      - ldc-dynamo

  ldc-dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: ldc-dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://ldc-dynamo:8000"
      AWS_REGION: "us-west-2"
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    depends_on:
      - ldc-dynamo
